id: A0DB1A5D1
base_file: f764F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:55:31.501853
  last_modified_at: 2022-05-30 20:55:31.501858
